global:
  # How frequently to scrape targets by default.
  # [ scrape_interval: <duration> | default = 1m ]
  scrape_interval: 10s

  # How long until a scrape request times out.
  # [ scrape_timeout: <duration> | default = 10s ]

  # How frequently to evaluate rules.
  # [ evaluation_interval: <duration> | default = 1m ]

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   [ <labelname>: <labelvalue> ... ]

  # File to which PromQL queries are logged.
  # Reloading the configuration will reopen the file.
  # [ query_log_file: <string> ]

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  # [ - <filepath_glob> ... ]

# A list of scrape configurations.
scrape_configs:
  # [ - <scrape_config> ... ]
  - job_name: 'prometheus'
    # metric path defaults to /metrics
    # metrics_path: /metrics
    # scheme defaults to http
    # scheme: http
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'grafana_metrics'
    static_configs:
      - targets:
          - 'grafana:3030'

  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'

# Alerting specifies settings related to the Alertmanager.
alerting:
  alert_relabel_configs:
    # [ - <relabel_config> ... ]
  alertmanagers:
    # [ - <alertmanager_config> ... ]

# Settings related to the remote write feature.
remote_write:
  # [ - <remote_write> ... ]

# Settings related to the remote read feature.
remote_read:
  # [ - <remote_read> ... ]

# Storage related settings that are runtime reloadable.
storage:
  # [ tsdb: <tsdb> ]
  # [ exemplars: <exemplars> ]
# Configures exporting traces.
# tracing:
# [ <tracing_config> ]
